"""add_pii_flags_to_jobs

Revision ID: b035bcbeeada
Revises: 84e8969e93b1
Create Date: 2025-11-30 10:55:40.330575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b035bcbeeada'
down_revision: Union[str, None] = '84e8969e93b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_action_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_resource', table_name='audit_logs')
    op.drop_index('idx_audit_user_ip_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_type', table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource_type', table_name='audit_logs')
    op.drop_index('ix_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_ip', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.add_column('jobs', sa.Column('contains_pii', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('pii_types', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('guardrail_flags', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'guardrail_flags')
    op.drop_column('jobs', 'pii_types')
    op.drop_column('jobs', 'contains_pii')
    op.create_table('audit_logs',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('user_ip', sa.VARCHAR(length=45), nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('resource_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_user_ip', 'audit_logs', ['user_ip'], unique=False)
    op.create_index('ix_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_logs_resource_type', 'audit_logs', ['resource_type'], unique=False)
    op.create_index('ix_audit_logs_resource_id', 'audit_logs', ['resource_id'], unique=False)
    op.create_index('ix_audit_logs_action_type', 'audit_logs', ['action_type'], unique=False)
    op.create_index('idx_audit_user_ip_timestamp', 'audit_logs', ['user_ip', 'timestamp'], unique=False)
    op.create_index('idx_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_action_timestamp', 'audit_logs', ['action_type', 'timestamp'], unique=False)
    # ### end Alembic commands ###
