"""add_dpdp_fields_to_jobs

Revision ID: e9b574cbc2d6
Revises: b035bcbeeada
Create Date: 2025-11-30 11:00:10.114638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9b574cbc2d6'
down_revision: Union[str, None] = 'b035bcbeeada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('data_principal_id', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('purpose_code', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('consent_verified', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('data_retention_policy', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'data_retention_policy')
    op.drop_column('jobs', 'consent_verified')
    op.drop_column('jobs', 'purpose_code')
    op.drop_column('jobs', 'data_principal_id')
    # ### end Alembic commands ###
